### ISSUE TITLE
Disable redirect for S3 storage backend

### ISSUE THREAD

**Issue by suppalapati13** [vmware/harbor-boshrelease#15]
We ran into an issue while deploying the harbor container registry using s3 as the storage backend. Our S3 buckets are locked down to allow only authorized sts/iam profiles to connect to them. To make it work, we need to disable redirect for the storage backend as documented here https://docs.docker.com/registry/configuration/#redirect

Issue
====
While pushing an image using `docker push`, it fails with an EOF error.

Temporary workaround
===================

Manually updating the `/var/vcap/jobs/harbor/packages/harbor-app/common/templates/registry/config.yml` file as shown below and restarting the `harbor` job allows pushing images to the registry.

```yaml
storage:
  cache:
    layerinfo: inmemory
  s3:
    region:  *****
    bucket: **********
    encrypt: true
    secure: true
    chunksize: 5242880
    rootdirectory: /harbor-container-registry
  maintenance:
    uploadpurging:
      enabled: false
  delete:
    enabled: true
  redirect:
    disable: true
```

Is this something that can be implemented by just updating the bosh release or require changes to the `harbor` package itself?
