### ISSUE TITLE
example for S3 

### ISSUE THREAD

**Issue by obeyler** [vmware/harbor-boshrelease#31]
Could you provide for an example of S3 configuration in manifest when use harbor-boshrelease ?
      config: region:((region)), bucket:((bucket) ,accesskey:((accesskey)) ,secretkey:((secretkey))
is it correct ?

 ```
 jobs:
  - name: harbor
    release: harbor-container-registry
    properties:
      hostname: ((hostname))
      db_password: ((harbor_db_password))
      admin_password: ((harbor_admin_password))
      clair_db_password: ((clair_db_password))
      with_clair: true
      with_notary: true
      #ui_url_protocol: http #default is https
      registry_storage_provider:
        name: s3
        config: region:((region)), bucket:((bucket) ,accesskey:((accesskey)) ,secretkey:((secretkey))
        redirect: false
```
