### ISSUE TITLE
wrong  version number in manifest

### ISSUE THREAD

**Issue by obeyler** [vmware/harbor-boshrelease#37]
```
releases:
- name: harbor-container-registry
  version: 1.6.0
  sha1: 5bb63d9b1cac2ae24e601d28c057af7dcb3abe8b
  url: https://storage.googleapis.com/harbor-bosh-releases/harbor-container-registry-1.6.2.tgz

```
there is a trouble between 1.6.0 version and tgz 1.6.2
