### ISSUE TITLE
Final releases or pre-compiled releases in the base manifest

### ISSUE THREAD

**Issue by drnic** [vmware/harbor-boshrelease#5]
I wanted to expand on one idea in #4 - final releases and pre-compiled releases, and making sure your base manifest has them embedded.

The desirable goal is for users to get started with just:

```
bosh -d harbor deploy manifests/harbor.yml
```

No manual uploading of bosh releases, no figuring out cloud-config stuff. The command above should "just work" for most BOSH users.

To achieve this, the `releases:` section needs to include final releases or pre-compiled final releases.

You've got some options:

```
releases:
- name: harbor-container-registry
  version: 1.0.0
  url: git+https://github.com/vmware/harbor-cff-bosh-release
```

Or using pre-build tgz, say from bosh.io

```
releases:
- name: harbor-container-registry
  version: 1.0.0
  url: https://bosh.io/d/github.com/vmware/harbor-cff-bosh-release?v=1.0.0
  sha1: 05305e3423aed79f0db0adb3e92c9ab426b58557
```

These two will ensure that `bosh deploy` automatically uploads v1.0.0 if the target BOSH director does not have it yet.

But, the user will then have to wait for each package to be compiled. And each time they bump their stemcell they will have to watch all packages be compiled again. This isn't necessary nor happy experience. It can be avoided for all users with pre-compiled releases.

See https://bosh.io/docs/compiled-releases/

You `bosh export-release` after you've created the final release in your CI pipeline, get the sha1, store the tgz to S3, and then update your `manifests/harbor.yml` with the details.

For example https://github.com/cloudfoundry-community/redis-boshrelease/blob/master/manifests/redis.yml#L54-L57

There are many CI ideas in https://github.com/cloudfoundry-community/redis-boshrelease/tree/master/ci that you might like to borrow to produce final releases (`shipit` job) and then create compiled releases. e.g. https://ci2.starkandwayne.com/teams/cfcommunity/pipelines/redis-boshrelease

/cc @cppforlife if you've got any other tips for the Harbor team?

**Comment by jessehu** [comment]
Fixed in  [Bump version to 1.5.0 and add pre-build final release](https://github.com/vmware/harbor-boshrelease/commit/3d38a02ca3fc7b4e7b9fc5b4182679ef7486c81e).
Please check https://github.com/vmware/harbor-boshrelease/blob/master/README.md#deploy-pre-build-final-release
```
You can deploy the published pre-build final release without creating a local dev release:

bosh -n -d harbor-deployment deploy manifests/harbor.yml -v hostname=harbor.local
```

https://github.com/vmware/harbor-boshrelease/blob/master/manifests/harbor.yml 
```
releases:
- name: harbor-container-registry
  version: 1.5.0
  sha1: ded9ed8a5e2efadc3aed26444710d8446483bd59
url: https://storage.googleapis.com/harbor-bosh-releases/harbor-container-registry-1.5.0.tgz
```
