### ISSUE TITLE
missing entry in spec file for property "admin_password_for_smoketest"

### ISSUE THREAD

**Issue by mandar14** [vmware/harbor-boshrelease#52]
Hi team, 
Trying to deploy Harbor as per README.md on AWS with necessary changes in Cloud-config.
Deployment broke-down with following error, 
`Link property admin_password_for_smoketest in template harbor is not defined in release spec`
 
Post investigation, found that,
Smoke-test  job in manifest consumes, harbor provider. Which provides bunch of properties.
https://github.com/vmware/harbor-boshrelease/blob/master/jobs/harbor/spec#L29-L40

An entry  for 'admin_password_for_smoketest' was missing in spec file.

Added same and created a dev-release, which results in successful deployment and passing of Smoketest.

did anyone else face this issue, if yes is this a correct solution or  any other solution is there.

**Comment by naulta** [comment]
I have run into this issue as well.

**Comment by hjaffan** [comment]
@mandar14  and @naulta  I did put a PR to fix this. I'm still waiting on someone to merge it. 
https://github.com/vmware/harbor-boshrelease/pull/53

**Comment by stonezdj** [comment]
In the deployment yml just defined the admin_password_for_smoketest is ok.
```
instance_groups:
- name: harbor-app
  azs: [az-1]
  instances: 1
  jobs:
  - name: harbor
    release: harbor-container-registry
    properties:
      hostname: ((hostname))
      db_password: ((harbor_db_password))
      admin_password: ((harbor_admin_password))
      admin_password_for_smoketest: ((harbor_admin_password))
```
