### ISSUE TITLE
Reduce expectations on cloud-config

### ISSUE THREAD

**Issue by drnic** [vmware/harbor-boshrelease#6]
As per #4 and #5, the goal of one base manifest is for `bosh deploy manifests/harbor.yml -d harbor` to "just work". 

This is made more likely if the base manifest does not put unexpected requirements on the cloud-config that any normal BOSH/CF/CFCR user wouldn't already have.

From one of your manifests:

```
instance_groups:
- name: harbor
  vm_type: standard
  persistent_disk_type: 20G
  networks:
  - name: default
    static_ips:
    - 10.112.123.31
```

Each of these three items can be changed to reduce the chance that a user will have an error when initially deploying:

* `vm_type:` can be changed to `vm_resource:` - see http://bosh.io/docs/manifest-v2/#instance-groups will delegate picking an instance type to the CPI, rather than require you to guess what vm_types are in a cloud-config
* `persistent_disk_type:` can change to `persistent_disk: 20480`. The CPI has default cloud_properties for each disk. The `persistent_disk_type:` attribute is only required if the deployer wants to have their disk have non-default cloud_properties. Leave that to them if they need it.
* `networks:` has a good assumption that all/most cloud-config has `name: default`. The one change to make is to remove `static_ips` from the base manifest. You don't know anything about a user's cloud-config and don't know what static_ips they have allocated.

/cc @cppforlife any other pro tips?
